### ISSUE TITLE
auto align to AMP using PATHfinding

### ISSUE THREAD

**Issue by MattD8957** [frc-862/rhapsody#29]
Come talk to me so we can set goals

**Comment by HeroSoLos** [comment]
bad

**Comment by HeroSoLos** [comment]
committig hard

**Comment by HeroSoLos** [comment]
josh code is ok(maybe)

**Comment by HeroSoLos** [comment]
lag + honest mistakes

**Comment by HeroSoLos** [comment]
y are there always like 16 people working on my project bruh

**Comment by HeroSoLos** [comment]
i may have forgotten about this

**Comment by HeroSoLos** [comment]
i shall keep forgetting about this
