### ISSUE TITLE
add ramp rate to all motors

### ISSUE THREAD

**Issue by WindowsVistaisCool** [frc-862/rhapsody#342]
https://api.ctr-electronics.com/phoenix6/release/java/com/ctre/phoenix6/configs/ClosedLoopRampsConfigs.html
and
https://api.ctr-electronics.com/phoenix6/release/java/com/ctre/phoenix6/configs/OpenLoopRampsConfigs.html

are the config options used to do this -- should apply a default in [ThunderBird](https://github.com/frc-862/thunder/blob/7988c833314e1d53976bb6ae3f6260f94b733212/hardware/ThunderBird.java#L31), can be overrode as required for specific motors. 

I recommend 0.1 (100ms) as a default.

**Comment by MattD8957** [comment]
Added to motors, need drivetrain

**Comment by MattD8957** [comment]
Works for all motors except drivetrain
